export interface IssueDTO {
  id: string
  title: string
  url: string
  project: string
  description: string
  timestamp: string
  inputTokens: number
  outputTokens: number
  cacheTokens: number
  cost: number
  time: number
  status: 'queued' | 'running' | 'succeeded' | 'failed'
}

// Simple text fixtures keyed by project slug
export const issuesByProject: Record<string, IssueDTO[]> = {
  'react-component-library': [
    {
      id: 'rcl-1',
      title: 'Button focus ring inconsistent',
      url: 'https://github.com/example/react-component-library/issues/1',
      project: 'react-component-library',
      description: 'Focus outline differs in Safari vs Chrome.',
      timestamp: '2025-11-05T09:15:00.000Z',
      inputTokens: 1250,
      outputTokens: 320,
      cacheTokens: 0,
      cost: 0.08,
      time: 42,
      status: 'succeeded',
    },
    {
      id: 'rcl-2',
      title: 'Modal traps focus incorrectly',
      url: 'https://github.com/example/react-component-library/issues/2',
      project: 'react-component-library',
      description: 'Keyboard users cannot escape modal with ESC in Firefox.',
      timestamp: '2025-11-06T11:00:00.000Z',
      inputTokens: 980,
      outputTokens: 250,
      cacheTokens: 10,
      cost: 0.06,
      time: 37,
      status: 'succeeded',
    },
    {
      id: 'rcl-3',
      title: 'Table virtualization breaks row selection',
      url: 'https://github.com/example/react-component-library/issues/3',
      project: 'react-component-library',
      description: 'Selecting rows while scrolling rapidly causes mismatched selection state.',
      timestamp: '2025-10-29T16:20:00.000Z',
      inputTokens: 1420,
      outputTokens: 410,
      cacheTokens: 0,
      cost: 0.09,
      time: 55,
      status: 'running',
    },
    {
      id: 'rcl-4',
      title: 'Dropdown closes on drag',
      url: 'https://github.com/example/react-component-library/issues/4',
      project: 'react-component-library',
      description: 'Dragging inside dropdown should not dismiss the menu.',
      timestamp: '2025-10-17T08:10:00.000Z',
      inputTokens: 700,
      outputTokens: 180,
      cacheTokens: 0,
      cost: 0.04,
      time: 22,
      status: 'queued',
    },
    {
      id: 'rcl-5',
      title: 'Select component loses focus on search',
      url: 'https://github.com/example/react-component-library/issues/5',
      project: 'react-component-library',
      description: 'Typing in the search input blurs the component intermittently.',
      timestamp: '2025-09-25T13:45:00.000Z',
      inputTokens: 620,
      outputTokens: 190,
      cacheTokens: 0,
      cost: 0.04,
      time: 19,
      status: 'succeeded',
    },
    {
      id: 'rcl-6',
      title: 'Tooltip flickers on hover between triggers',
      url: 'https://github.com/example/react-component-library/issues/6',
      project: 'react-component-library',
      description: 'Moving between two triggers causes rapid unmount/remount.',
      timestamp: '2025-10-03T10:00:00.000Z',
      inputTokens: 540,
      outputTokens: 160,
      cacheTokens: 0,
      cost: 0.03,
      time: 14,
      status: 'succeeded',
    },
    {
      id: 'rcl-7',
      title: 'FormField label id mismatch',
      url: 'https://github.com/example/react-component-library/issues/7',
      project: 'react-component-library',
      description: '`htmlFor` does not match input `id` when nested in arrays.',
      timestamp: '2025-08-18T09:22:00.000Z',
      inputTokens: 500,
      outputTokens: 140,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'failed',
    },
    {
      id: 'rcl-8',
      title: 'Theme switcher ignores system preference',
      url: 'https://github.com/example/react-component-library/issues/8',
      project: 'react-component-library',
      description: '`prefers-color-scheme` is not applied on first paint.',
      timestamp: '2025-11-01T07:30:00.000Z',
      inputTokens: 880,
      outputTokens: 230,
      cacheTokens: 0,
      cost: 0.05,
      time: 28,
      status: 'succeeded',
    },
    {
      id: 'rcl-9',
      title: 'Tabs overflow not accessible',
      url: 'https://github.com/example/react-component-library/issues/9',
      project: 'react-component-library',
      description: 'Overflowed tabs are not keyboard reachable.',
      timestamp: '2025-07-22T15:05:00.000Z',
      inputTokens: 760,
      outputTokens: 200,
      cacheTokens: 0,
      cost: 0.04,
      time: 21,
      status: 'queued',
    },
    {
      id: 'rcl-10',
      title: 'Popover positioning off in RTL',
      url: 'https://github.com/example/react-component-library/issues/10',
      project: 'react-component-library',
      description: 'Floating-ui config not respecting `dir=rtl`.',
      timestamp: '2025-10-11T12:12:00.000Z',
      inputTokens: 1010,
      outputTokens: 280,
      cacheTokens: 20,
      cost: 0.06,
      time: 33,
      status: 'succeeded',
    },
  ],
  'design-tokens': [
    {
      id: 'dt-1',
      title: 'Token sync script fails on Windows',
      url: 'https://github.com/example/design-tokens/issues/12',
      project: 'design-tokens',
      description: 'Path separators break glob imports.',
      timestamp: '2025-10-20T13:00:00.000Z',
      inputTokens: 800,
      outputTokens: 210,
      cacheTokens: 50,
      cost: 0.05,
      time: 30,
      status: 'running',
    },
    {
      id: 'dt-2',
      title: 'Color contrast fails for secondary button',
      url: 'https://github.com/example/design-tokens/issues/13',
      project: 'design-tokens',
      description: 'Secondary palette fails WCAG AA on light theme.',
      timestamp: '2025-11-02T10:10:00.000Z',
      inputTokens: 610,
      outputTokens: 170,
      cacheTokens: 0,
      cost: 0.04,
      time: 18,
      status: 'succeeded',
    },
    {
      id: 'dt-3',
      title: 'Shadow tokens inconsistent across platforms',
      url: 'https://github.com/example/design-tokens/issues/14',
      project: 'design-tokens',
      description: 'Android elevation mapping does not match web shadows.',
      timestamp: '2025-09-14T08:00:00.000Z',
      inputTokens: 720,
      outputTokens: 195,
      cacheTokens: 0,
      cost: 0.04,
      time: 24,
      status: 'queued',
    },
    {
      id: 'dt-4',
      title: 'Typography scale missing 2xl',
      url: 'https://github.com/example/design-tokens/issues/15',
      project: 'design-tokens',
      description: '`font-size` token for 2xl not exported to Figma plugin.',
      timestamp: '2025-08-19T17:40:00.000Z',
      inputTokens: 500,
      outputTokens: 140,
      cacheTokens: 0,
      cost: 0.03,
      time: 16,
      status: 'succeeded',
    },
    {
      id: 'dt-5',
      title: 'Dark theme elevation too strong',
      url: 'https://github.com/example/design-tokens/issues/16',
      project: 'design-tokens',
      description: 'Backdrop blur and opacity produce muddy surfaces.',
      timestamp: '2025-11-07T09:00:00.000Z',
      inputTokens: 850,
      outputTokens: 210,
      cacheTokens: 0,
      cost: 0.05,
      time: 26,
      status: 'running',
    },
    {
      id: 'dt-6',
      title: 'Spacing scale lacks micro steps',
      url: 'https://github.com/example/design-tokens/issues/17',
      project: 'design-tokens',
      description: 'Need 2px and 6px steps for fine-grained layouts.',
      timestamp: '2025-07-30T12:12:00.000Z',
      inputTokens: 470,
      outputTokens: 130,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'dt-7',
      title: 'Alias tokens not updating in consumers',
      url: 'https://github.com/example/design-tokens/issues/18',
      project: 'design-tokens',
      description: 'Publish script skips `dist/json` in minor releases.',
      timestamp: '2025-10-01T06:33:00.000Z',
      inputTokens: 690,
      outputTokens: 180,
      cacheTokens: 0,
      cost: 0.04,
      time: 20,
      status: 'failed',
    },
    {
      id: 'dt-8',
      title: 'Design token docs outdated',
      url: 'https://github.com/example/design-tokens/issues/19',
      project: 'design-tokens',
      description: 'Docs still reference style-dictionary v3.',
      timestamp: '2025-09-10T10:00:00.000Z',
      inputTokens: 400,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.02,
      time: 10,
      status: 'queued',
    },
    {
      id: 'dt-9',
      title: 'Figma plugin auth expires too early',
      url: 'https://github.com/example/design-tokens/issues/20',
      project: 'design-tokens',
      description: 'Token refresh not called during long sessions.',
      timestamp: '2025-10-22T14:44:00.000Z',
      inputTokens: 560,
      outputTokens: 160,
      cacheTokens: 0,
      cost: 0.03,
      time: 14,
      status: 'succeeded',
    },
    {
      id: 'dt-10',
      title: 'Platform-specific overrides strategy',
      url: 'https://github.com/example/design-tokens/issues/21',
      project: 'design-tokens',
      description: 'Define approach for iOS vs Android semantic tokens.',
      timestamp: '2025-11-09T09:30:00.000Z',
      inputTokens: 920,
      outputTokens: 240,
      cacheTokens: 0,
      cost: 0.06,
      time: 29,
      status: 'running',
    },
  ],
  'docs-site': [
    {
      id: 'ds-1',
      title: 'Broken link in Getting Started',
      url: 'https://github.com/example/docs-site/issues/1',
      project: 'docs-site',
      description: 'The Quickstart points to a removed page.',
      timestamp: '2025-11-01T08:00:00.000Z',
      inputTokens: 300,
      outputTokens: 90,
      cacheTokens: 0,
      cost: 0.02,
      time: 6,
      status: 'succeeded',
    },
    {
      id: 'ds-2',
      title: 'Search index not updating on deploy',
      url: 'https://github.com/example/docs-site/issues/2',
      project: 'docs-site',
      description: 'Algolia sync job fails intermittently.',
      timestamp: '2025-11-03T09:20:00.000Z',
      inputTokens: 520,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 13,
      status: 'running',
    },
    {
      id: 'ds-3',
      title: 'Dark mode images missing',
      url: 'https://github.com/example/docs-site/issues/3',
      project: 'docs-site',
      description: 'Screenshots unreadable in dark theme.',
      timestamp: '2025-10-28T12:45:00.000Z',
      inputTokens: 440,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'queued',
    },
    {
      id: 'ds-4',
      title: 'Nav sidebar scroll position resets',
      url: 'https://github.com/example/docs-site/issues/4',
      project: 'docs-site',
      description: 'On route change, sidebar scroll should be preserved.',
      timestamp: '2025-09-12T10:00:00.000Z',
      inputTokens: 380,
      outputTokens: 110,
      cacheTokens: 0,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'ds-5',
      title: 'Code blocks lack copy button',
      url: 'https://github.com/example/docs-site/issues/5',
      project: 'docs-site',
      description: 'Add copy-to-clipboard to fenced blocks.',
      timestamp: '2025-08-05T14:33:00.000Z',
      inputTokens: 300,
      outputTokens: 90,
      cacheTokens: 0,
      cost: 0.02,
      time: 7,
      status: 'succeeded',
    },
    {
      id: 'ds-6',
      title: 'Versioned docs build fails',
      url: 'https://github.com/example/docs-site/issues/6',
      project: 'docs-site',
      description: 'Docusaurus plugin-content-docs throws on missing sidebar.',
      timestamp: '2025-10-10T09:18:00.000Z',
      inputTokens: 560,
      outputTokens: 160,
      cacheTokens: 0,
      cost: 0.03,
      time: 15,
      status: 'failed',
    },
    {
      id: 'ds-7',
      title: 'RSS feed timestamp incorrect',
      url: 'https://github.com/example/docs-site/issues/7',
      project: 'docs-site',
      description: 'Dates are in local time instead of UTC.',
      timestamp: '2025-11-08T07:00:00.000Z',
      inputTokens: 420,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.03,
      time: 11,
      status: 'running',
    },
    {
      id: 'ds-8',
      title: 'Sitemap excludes /blog',
      url: 'https://github.com/example/docs-site/issues/8',
      project: 'docs-site',
      description: 'SEO plugin misconfigured for blog route.',
      timestamp: '2025-07-21T10:10:00.000Z',
      inputTokens: 350,
      outputTokens: 100,
      cacheTokens: 0,
      cost: 0.02,
      time: 8,
      status: 'queued',
    },
    {
      id: 'ds-9',
      title: 'Accessibility: skip link hidden off-screen',
      url: 'https://github.com/example/docs-site/issues/9',
      project: 'docs-site',
      description: 'Skip link not visible on focus for keyboard users.',
      timestamp: '2025-09-29T16:40:00.000Z',
      inputTokens: 480,
      outputTokens: 140,
      cacheTokens: 0,
      cost: 0.03,
      time: 13,
      status: 'succeeded',
    },
    {
      id: 'ds-10',
      title: 'Broken 404 page styling',
      url: 'https://github.com/example/docs-site/issues/10',
      project: 'docs-site',
      description: 'Tailwind classes missing from 404 route.',
      timestamp: '2025-11-11T18:22:00.000Z',
      inputTokens: 520,
      outputTokens: 160,
      cacheTokens: 0,
      cost: 0.03,
      time: 14,
      status: 'succeeded',
    },
  ],
  'storybook': [
    {
      id: 'sb-1',
      title: 'MDX stories not rendering in React 19',
      url: 'https://github.com/example/storybook/issues/1',
      project: 'storybook',
      description: 'Compat layer required for new JSX runtime.',
      timestamp: '2025-10-31T10:00:00.000Z',
      inputTokens: 900,
      outputTokens: 240,
      cacheTokens: 0,
      cost: 0.05,
      time: 25,
      status: 'running',
    },
    {
      id: 'sb-2',
      title: 'Docs addon breaks HMR',
      url: 'https://github.com/example/storybook/issues/2',
      project: 'storybook',
      description: 'Fast Refresh is disabled when docs addon is enabled.',
      timestamp: '2025-11-02T12:10:00.000Z',
      inputTokens: 620,
      outputTokens: 170,
      cacheTokens: 0,
      cost: 0.04,
      time: 18,
      status: 'succeeded',
    },
    {
      id: 'sb-3',
      title: 'Theming via CSS vars not applied in iframe',
      url: 'https://github.com/example/storybook/issues/3',
      project: 'storybook',
      description: 'Preview head missing variable injection.',
      timestamp: '2025-09-14T09:40:00.000Z',
      inputTokens: 540,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 14,
      status: 'queued',
    },
    {
      id: 'sb-4',
      title: 'Chromatic snapshots flakey',
      url: 'https://github.com/example/storybook/issues/4',
      project: 'storybook',
      description: 'Animations not disabled during snapshot run.',
      timestamp: '2025-08-20T08:00:00.000Z',
      inputTokens: 500,
      outputTokens: 140,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'failed',
    },
    {
      id: 'sb-5',
      title: 'Story sorting incorrect with groups',
      url: 'https://github.com/example/storybook/issues/5',
      project: 'storybook',
      description: 'Custom sort not stable across reloads.',
      timestamp: '2025-10-05T11:20:00.000Z',
      inputTokens: 480,
      outputTokens: 135,
      cacheTokens: 0,
      cost: 0.03,
      time: 11,
      status: 'succeeded',
    },
    {
      id: 'sb-6',
      title: 'Vite builder fails on TS path aliases',
      url: 'https://github.com/example/storybook/issues/6',
      project: 'storybook',
      description: '`moduleResolution: bundler` needs `vite-tsconfig-paths` plugin.',
      timestamp: '2025-11-06T09:30:00.000Z',
      inputTokens: 620,
      outputTokens: 170,
      cacheTokens: 0,
      cost: 0.04,
      time: 17,
      status: 'running',
    },
    {
      id: 'sb-7',
      title: 'A11y addon reports false positives',
      url: 'https://github.com/example/storybook/issues/7',
      project: 'storybook',
      description: 'Landmark roles missing in isolated iframes.',
      timestamp: '2025-10-12T13:00:00.000Z',
      inputTokens: 410,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'sb-8',
      title: 'Controls addon not updating args',
      url: 'https://github.com/example/storybook/issues/8',
      project: 'storybook',
      description: 'ArgTypes lost when composing stories.',
      timestamp: '2025-09-02T10:15:00.000Z',
      inputTokens: 430,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.02,
      time: 9,
      status: 'queued',
    },
    {
      id: 'sb-9',
      title: 'Types not emitted for story files',
      url: 'https://github.com/example/storybook/issues/9',
      project: 'storybook',
      description: 'TS project references not followed by builder.',
      timestamp: '2025-07-18T08:44:00.000Z',
      inputTokens: 520,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 10,
      status: 'succeeded',
    },
    {
      id: 'sb-10',
      title: 'Storyshots migration plan',
      url: 'https://github.com/example/storybook/issues/10',
      project: 'storybook',
      description: 'Decide on Playwright for visual regression tests.',
      timestamp: '2025-11-09T07:55:00.000Z',
      inputTokens: 800,
      outputTokens: 210,
      cacheTokens: 0,
      cost: 0.05,
      time: 20,
      status: 'running',
    },
  ],
  'ci-pipeline': [
    {
      id: 'ci-1',
      title: 'Caching not used in Bun install',
      url: 'https://github.com/example/ci-pipeline/issues/1',
      project: 'ci-pipeline',
      description: 'Enable persistent cache between jobs.',
      timestamp: '2025-10-22T09:00:00.000Z',
      inputTokens: 520,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'ci-2',
      title: 'Flaky Playwright tests on macOS runners',
      url: 'https://github.com/example/ci-pipeline/issues/2',
      project: 'ci-pipeline',
      description: 'Increase timeouts and disable GPU.',
      timestamp: '2025-11-04T10:10:00.000Z',
      inputTokens: 680,
      outputTokens: 180,
      cacheTokens: 0,
      cost: 0.04,
      time: 16,
      status: 'running',
    },
    {
      id: 'ci-3',
      title: 'Docker layer caching not effective',
      url: 'https://github.com/example/ci-pipeline/issues/3',
      project: 'ci-pipeline',
      description: 'Reorder steps to maximize cache hits.',
      timestamp: '2025-09-14T12:30:00.000Z',
      inputTokens: 500,
      outputTokens: 140,
      cacheTokens: 0,
      cost: 0.03,
      time: 11,
      status: 'succeeded',
    },
    {
      id: 'ci-4',
      title: 'Matrix builds exceed concurrency quota',
      url: 'https://github.com/example/ci-pipeline/issues/4',
      project: 'ci-pipeline',
      description: 'Introduce job-level throttling and skip patterns.',
      timestamp: '2025-08-20T08:00:00.000Z',
      inputTokens: 460,
      outputTokens: 130,
      cacheTokens: 0,
      cost: 0.02,
      time: 9,
      status: 'queued',
    },
    {
      id: 'ci-5',
      title: 'Release job fails to upload assets',
      url: 'https://github.com/example/ci-pipeline/issues/5',
      project: 'ci-pipeline',
      description: 'GitHub token missing `packages:write` scope.',
      timestamp: '2025-11-07T07:40:00.000Z',
      inputTokens: 740,
      outputTokens: 200,
      cacheTokens: 0,
      cost: 0.05,
      time: 18,
      status: 'failed',
    },
    {
      id: 'ci-6',
      title: 'Cache restore too slow',
      url: 'https://github.com/example/ci-pipeline/issues/6',
      project: 'ci-pipeline',
      description: 'Use tar compression and split archives.',
      timestamp: '2025-10-03T10:00:00.000Z',
      inputTokens: 520,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'ci-7',
      title: 'PR labels automation',
      url: 'https://github.com/example/ci-pipeline/issues/7',
      project: 'ci-pipeline',
      description: 'Automatically apply labels based on paths.',
      timestamp: '2025-09-01T11:11:00.000Z',
      inputTokens: 430,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'ci-8',
      title: 'Secrets scanning in CI',
      url: 'https://github.com/example/ci-pipeline/issues/8',
      project: 'ci-pipeline',
      description: 'Add gitleaks pre-commit and CI step.',
      timestamp: '2025-07-12T14:20:00.000Z',
      inputTokens: 480,
      outputTokens: 130,
      cacheTokens: 0,
      cost: 0.03,
      time: 10,
      status: 'queued',
    },
    {
      id: 'ci-9',
      title: 'Reusable workflows DRY-up',
      url: 'https://github.com/example/ci-pipeline/issues/9',
      project: 'ci-pipeline',
      description: 'Extract common steps to called workflows.',
      timestamp: '2025-10-16T09:09:00.000Z',
      inputTokens: 560,
      outputTokens: 160,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'ci-10',
      title: 'Self-hosted runners evaluation',
      url: 'https://github.com/example/ci-pipeline/issues/10',
      project: 'ci-pipeline',
      description: 'Assess cost and maintenance overhead.',
      timestamp: '2025-11-10T10:10:00.000Z',
      inputTokens: 820,
      outputTokens: 220,
      cacheTokens: 0,
      cost: 0.05,
      time: 20,
      status: 'running',
    },
  ],
  'icon-pack': [
    {
      id: 'ip-1',
      title: 'Missing 20px size for several icons',
      url: 'https://github.com/example/icon-pack/issues/1',
      project: 'icon-pack',
      description: 'Add medium size variants for new set.',
      timestamp: '2025-10-01T10:00:00.000Z',
      inputTokens: 420,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.02,
      time: 8,
      status: 'succeeded',
    },
    {
      id: 'ip-2',
      title: 'SVGs not optimized',
      url: 'https://github.com/example/icon-pack/issues/2',
      project: 'icon-pack',
      description: 'Run SVGO and remove unnecessary attributes.',
      timestamp: '2025-11-03T09:30:00.000Z',
      inputTokens: 500,
      outputTokens: 140,
      cacheTokens: 0,
      cost: 0.03,
      time: 10,
      status: 'running',
    },
    {
      id: 'ip-3',
      title: 'Icons not centered on baseline',
      url: 'https://github.com/example/icon-pack/issues/3',
      project: 'icon-pack',
      description: 'Adjust viewBox and stroke alignment.',
      timestamp: '2025-09-18T12:45:00.000Z',
      inputTokens: 460,
      outputTokens: 130,
      cacheTokens: 0,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'ip-4',
      title: 'Build script fails on Node 22',
      url: 'https://github.com/example/icon-pack/issues/4',
      project: 'icon-pack',
      description: 'Update esbuild and remove deprecated flags.',
      timestamp: '2025-08-25T07:20:00.000Z',
      inputTokens: 520,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 11,
      status: 'failed',
    },
    {
      id: 'ip-5',
      title: 'Add duotone variants',
      url: 'https://github.com/example/icon-pack/issues/5',
      project: 'icon-pack',
      description: 'Introduce two-tone style for emphasis icons.',
      timestamp: '2025-10-08T16:16:00.000Z',
      inputTokens: 600,
      outputTokens: 160,
      cacheTokens: 0,
      cost: 0.04,
      time: 14,
      status: 'queued',
    },
    {
      id: 'ip-6',
      title: 'Tree-shaking not working in consumers',
      url: 'https://github.com/example/icon-pack/issues/6',
      project: 'icon-pack',
      description: 'Ensure `sideEffects: false` and ESM entry points.',
      timestamp: '2025-10-30T09:00:00.000Z',
      inputTokens: 650,
      outputTokens: 170,
      cacheTokens: 0,
      cost: 0.04,
      time: 15,
      status: 'succeeded',
    },
    {
      id: 'ip-7',
      title: 'Stroke widths inconsistent',
      url: 'https://github.com/example/icon-pack/issues/7',
      project: 'icon-pack',
      description: 'Normalize strokes to even pixels for crispness.',
      timestamp: '2025-07-14T10:10:00.000Z',
      inputTokens: 400,
      outputTokens: 120,
      cacheTokens: 0,
      cost: 0.02,
      time: 8,
      status: 'succeeded',
    },
    {
      id: 'ip-8',
      title: 'Missing RTL-mirrored icons',
      url: 'https://github.com/example/icon-pack/issues/8',
      project: 'icon-pack',
      description: 'Provide flipped versions for directional icons.',
      timestamp: '2025-09-29T11:50:00.000Z',
      inputTokens: 470,
      outputTokens: 130,
      cacheTokens: 0,
      cost: 0.03,
      time: 10,
      status: 'queued',
    },
    {
      id: 'ip-9',
      title: 'Add license headers',
      url: 'https://github.com/example/icon-pack/issues/9',
      project: 'icon-pack',
      description: 'Ensure all SVGs contain SPDX headers.',
      timestamp: '2025-11-06T06:40:00.000Z',
      inputTokens: 520,
      outputTokens: 150,
      cacheTokens: 0,
      cost: 0.03,
      time: 12,
      status: 'running',
    },
    {
      id: 'ip-10',
      title: 'Icon preview site',
      url: 'https://github.com/example/icon-pack/issues/10',
      project: 'icon-pack',
      description: 'Create searchable gallery with filters.',
      timestamp: '2025-11-09T12:00:00.000Z',
      inputTokens: 800,
      outputTokens: 210,
      cacheTokens: 0,
      cost: 0.05,
      time: 19,
      status: 'running',
    },
  ],
}
