export interface IssueDTO {
  id: string
  title: string
  url: string
  project: string
  timestamp: string
  inputTokens: number
  outputTokens: number
  cacheTokens: number
  cost: number
  time: number
  status: 'queued' | 'running' | 'succeeded' | 'failed'
}

// Simple text fixtures keyed by project slug
const issuesByProjectRaw: Record<string, IssueDTO[]> = {
  'react-component-library': [
    {
      id: 'rcl-1',
      title: 'Button focus ring inconsistent',
      url: 'https://github.com/example/react-component-library/issues/1',
      project: 'react-component-library',
      timestamp: '2025-11-05T09:15:00.000Z',
      inputTokens: 4123,
      outputTokens: 1376,
      cacheTokens: 5299,
      cost: 0.08,
      time: 42,
      status: 'succeeded',
    },
    {
      id: 'rcl-2',
      title: 'Modal traps focus incorrectly',
      url: 'https://github.com/example/react-component-library/issues/2',
      project: 'react-component-library',
      timestamp: '2025-11-06T11:00:00.000Z',
      inputTokens: 5987,
      outputTokens: 2144,
      cacheTokens: 10033,
      cost: 0.06,
      time: 37,
      status: 'succeeded',
    },
    {
      id: 'rcl-3',
      title: 'Table virtualization breaks row selection',
      url: 'https://github.com/example/react-component-library/issues/3',
      project: 'react-component-library',
      timestamp: '2025-10-29T16:20:00.000Z',
      inputTokens: 7234,
      outputTokens: 2210,
      cacheTokens: 13021,
      cost: 0.09,
      time: 55,
      status: 'running',
    },
    {
      id: 'rcl-4',
      title: 'Dropdown closes on drag',
      url: 'https://github.com/example/react-component-library/issues/4',
      project: 'react-component-library',
      timestamp: '2025-10-17T08:10:00.000Z',
      inputTokens: 3156,
      outputTokens: 1475,
      cacheTokens: 6221,
      cost: 0.04,
      time: 22,
      status: 'queued',
    },
    {
      id: 'rcl-5',
      title: 'Select component loses focus on search',
      url: 'https://github.com/example/react-component-library/issues/5',
      project: 'react-component-library',
      timestamp: '2025-09-25T13:45:00.000Z',
      inputTokens: 2842,
      outputTokens: 1503,
      cacheTokens: 5097,
      cost: 0.04,
      time: 19,
      status: 'succeeded',
    },
    {
      id: 'rcl-6',
      title: 'Tooltip flickers on hover between triggers',
      url: 'https://github.com/example/react-component-library/issues/6',
      project: 'react-component-library',
      timestamp: '2025-10-03T10:00:00.000Z',
      inputTokens: 3619,
      outputTokens: 1762,
      cacheTokens: 6888,
      cost: 0.03,
      time: 14,
      status: 'succeeded',
    },
    {
      id: 'rcl-7',
      title: 'FormField label id mismatch',
      url: 'https://github.com/example/react-component-library/issues/7',
      project: 'react-component-library',
      timestamp: '2025-08-18T09:22:00.000Z',
      inputTokens: 4397,
      outputTokens: 1639,
      cacheTokens: 7120,
      cost: 0.03,
      time: 12,
      status: 'failed',
    },
    {
      id: 'rcl-8',
      title: 'Theme switcher ignores system preference',
      url: 'https://github.com/example/react-component-library/issues/8',
      project: 'react-component-library',
      timestamp: '2025-11-01T07:30:00.000Z',
      inputTokens: 5011,
      outputTokens: 1837,
      cacheTokens: 8459,
      cost: 0.05,
      time: 28,
      status: 'succeeded',
    },
    {
      id: 'rcl-9',
      title: 'Tabs overflow not accessible',
      url: 'https://github.com/example/react-component-library/issues/9',
      project: 'react-component-library',
      timestamp: '2025-07-22T15:05:00.000Z',
      inputTokens: 3329,
      outputTokens: 1512,
      cacheTokens: 6755,
      cost: 0.04,
      time: 21,
      status: 'queued',
    },
    {
      id: 'rcl-10',
      title: 'Popover positioning off in RTL',
      url: 'https://github.com/example/react-component-library/issues/10',
      project: 'react-component-library',
      timestamp: '2025-10-11T12:12:00.000Z',
      inputTokens: 6542,
      outputTokens: 2083,
      cacheTokens: 12071,
      cost: 0.06,
      time: 33,
      status: 'succeeded',
    },
  ],
  'design-tokens': [
    {
      id: 'dt-1',
      title: 'Token sync script fails on Windows',
      url: 'https://github.com/example/design-tokens/issues/12',
      project: 'design-tokens',
      timestamp: '2025-10-20T13:00:00.000Z',
      inputTokens: 4877,
      outputTokens: 1695,
      cacheTokens: 9022,
      cost: 0.05,
      time: 30,
      status: 'running',
    },
    {
      id: 'dt-2',
      title: 'Color contrast fails for secondary button',
      url: 'https://github.com/example/design-tokens/issues/13',
      project: 'design-tokens',
      timestamp: '2025-11-02T10:10:00.000Z',
      inputTokens: 5440,
      outputTokens: 1902,
      cacheTokens: 10011,
      cost: 0.04,
      time: 18,
      status: 'succeeded',
    },
    {
      id: 'dt-3',
      title: 'Shadow tokens inconsistent across platforms',
      url: 'https://github.com/example/design-tokens/issues/14',
      project: 'design-tokens',
      timestamp: '2025-09-14T08:00:00.000Z',
      inputTokens: 4316,
      outputTokens: 1610,
      cacheTokens: 8099,
      cost: 0.04,
      time: 24,
      status: 'queued',
    },
    {
      id: 'dt-4',
      title: 'Typography scale missing 2xl',
      url: 'https://github.com/example/design-tokens/issues/15',
      project: 'design-tokens',
      timestamp: '2025-08-19T17:40:00.000Z',
      inputTokens: 2891,
      outputTokens: 1397,
      cacheTokens: 5228,
      cost: 0.03,
      time: 16,
      status: 'succeeded',
    },
    {
      id: 'dt-5',
      title: 'Dark theme elevation too strong',
      url: 'https://github.com/example/design-tokens/issues/16',
      project: 'design-tokens',
      timestamp: '2025-11-07T09:00:00.000Z',
      inputTokens: 6124,
      outputTokens: 2068,
      cacheTokens: 11007,
      cost: 0.05,
      time: 26,
      status: 'running',
    },
    {
      id: 'dt-6',
      title: 'Spacing scale lacks micro steps',
      url: 'https://github.com/example/design-tokens/issues/17',
      project: 'design-tokens',
      timestamp: '2025-07-30T12:12:00.000Z',
      inputTokens: 3475,
      outputTokens: 1471,
      cacheTokens: 7033,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'dt-7',
      title: 'Alias tokens not updating in consumers',
      url: 'https://github.com/example/design-tokens/issues/18',
      project: 'design-tokens',
      timestamp: '2025-10-01T06:33:00.000Z',
      inputTokens: 4582,
      outputTokens: 1714,
      cacheTokens: 8897,
      cost: 0.04,
      time: 20,
      status: 'failed',
    },
    {
      id: 'dt-8',
      title: 'Design token docs outdated',
      url: 'https://github.com/example/design-tokens/issues/19',
      project: 'design-tokens',
      timestamp: '2025-09-10T10:00:00.000Z',
      inputTokens: 3017,
      outputTokens: 1299,
      cacheTokens: 6205,
      cost: 0.02,
      time: 10,
      status: 'queued',
    },
    {
      id: 'dt-9',
      title: 'Figma plugin auth expires too early',
      url: 'https://github.com/example/design-tokens/issues/20',
      project: 'design-tokens',
      timestamp: '2025-10-22T14:44:00.000Z',
      inputTokens: 3766,
      outputTokens: 1544,
      cacheTokens: 7521,
      cost: 0.03,
      time: 14,
      status: 'succeeded',
    },
    {
      id: 'dt-10',
      title: 'Platform-specific overrides strategy',
      url: 'https://github.com/example/design-tokens/issues/21',
      project: 'design-tokens',
      timestamp: '2025-11-09T09:30:00.000Z',
      inputTokens: 5981,
      outputTokens: 2033,
      cacheTokens: 11298,
      cost: 0.06,
      time: 29,
      status: 'running',
    },
  ],
  'docs-site': [
    {
      id: 'ds-1',
      title: 'Broken link in Getting Started',
      url: 'https://github.com/example/docs-site/issues/1',
      project: 'docs-site',
      timestamp: '2025-11-01T08:00:00.000Z',
      inputTokens: 2190,
      outputTokens: 1183,
      cacheTokens: 4167,
      cost: 0.02,
      time: 6,
      status: 'succeeded',
    },
    {
      id: 'ds-2',
      title: 'Search index not updating on deploy',
      url: 'https://github.com/example/docs-site/issues/2',
      project: 'docs-site',
      timestamp: '2025-11-03T09:20:00.000Z',
      inputTokens: 4879,
      outputTokens: 1670,
      cacheTokens: 9655,
      cost: 0.03,
      time: 13,
      status: 'running',
    },
    {
      id: 'ds-3',
      title: 'Dark mode images missing',
      url: 'https://github.com/example/docs-site/issues/3',
      project: 'docs-site',
      timestamp: '2025-10-28T12:45:00.000Z',
      inputTokens: 3325,
      outputTokens: 1411,
      cacheTokens: 6766,
      cost: 0.03,
      time: 12,
      status: 'queued',
    },
    {
      id: 'ds-4',
      title: 'Nav sidebar scroll position resets',
      url: 'https://github.com/example/docs-site/issues/4',
      project: 'docs-site',
      timestamp: '2025-09-12T10:00:00.000Z',
      inputTokens: 2749,
      outputTokens: 1320,
      cacheTokens: 5381,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'ds-5',
      title: 'Code blocks lack copy button',
      url: 'https://github.com/example/docs-site/issues/5',
      project: 'docs-site',
      timestamp: '2025-08-05T14:33:00.000Z',
      inputTokens: 2067,
      outputTokens: 1109,
      cacheTokens: 4098,
      cost: 0.02,
      time: 7,
      status: 'succeeded',
    },
    {
      id: 'ds-6',
      title: 'Versioned docs build fails',
      url: 'https://github.com/example/docs-site/issues/6',
      project: 'docs-site',
      timestamp: '2025-10-10T09:18:00.000Z',
      inputTokens: 4188,
      outputTokens: 1517,
      cacheTokens: 8206,
      cost: 0.03,
      time: 15,
      status: 'failed',
    },
    {
      id: 'ds-7',
      title: 'RSS feed timestamp incorrect',
      url: 'https://github.com/example/docs-site/issues/7',
      project: 'docs-site',
      timestamp: '2025-11-08T07:00:00.000Z',
      inputTokens: 3655,
      outputTokens: 1402,
      cacheTokens: 7421,
      cost: 0.03,
      time: 11,
      status: 'running',
    },
    {
      id: 'ds-8',
      title: 'Sitemap excludes /blog',
      url: 'https://github.com/example/docs-site/issues/8',
      project: 'docs-site',
      timestamp: '2025-07-21T10:10:00.000Z',
      inputTokens: 2576,
      outputTokens: 1218,
      cacheTokens: 4983,
      cost: 0.02,
      time: 8,
      status: 'queued',
    },
    {
      id: 'ds-9',
      title: 'Accessibility: skip link hidden off-screen',
      url: 'https://github.com/example/docs-site/issues/9',
      project: 'docs-site',
      timestamp: '2025-09-29T16:40:00.000Z',
      inputTokens: 3411,
      outputTokens: 1362,
      cacheTokens: 7019,
      cost: 0.03,
      time: 13,
      status: 'succeeded',
    },
    {
      id: 'ds-10',
      title: 'Broken 404 page styling',
      url: 'https://github.com/example/docs-site/issues/10',
      project: 'docs-site',
      timestamp: '2025-11-11T18:22:00.000Z',
      inputTokens: 4933,
      outputTokens: 1644,
      cacheTokens: 10077,
      cost: 0.03,
      time: 14,
      status: 'succeeded',
    },
  ],
  'storybook': [
    {
      id: 'sb-1',
      title: 'MDX stories not rendering in React 19',
      url: 'https://github.com/example/storybook/issues/1',
      project: 'storybook',
      timestamp: '2025-10-31T10:00:00.000Z',
      inputTokens: 5299,
      outputTokens: 1821,
      cacheTokens: 11002,
      cost: 0.05,
      time: 25,
      status: 'running',
    },
    {
      id: 'sb-2',
      title: 'Docs addon breaks HMR',
      url: 'https://github.com/example/storybook/issues/2',
      project: 'storybook',
      timestamp: '2025-11-02T12:10:00.000Z',
      inputTokens: 4111,
      outputTokens: 1607,
      cacheTokens: 8244,
      cost: 0.04,
      time: 18,
      status: 'succeeded',
    },
    {
      id: 'sb-3',
      title: 'Theming via CSS vars not applied in iframe',
      url: 'https://github.com/example/storybook/issues/3',
      project: 'storybook',
      timestamp: '2025-09-14T09:40:00.000Z',
      inputTokens: 3046,
      outputTokens: 1304,
      cacheTokens: 6099,
      cost: 0.03,
      time: 14,
      status: 'queued',
    },
    {
      id: 'sb-4',
      title: 'Chromatic snapshots flakey',
      url: 'https://github.com/example/storybook/issues/4',
      project: 'storybook',
      timestamp: '2025-08-20T08:00:00.000Z',
      inputTokens: 2677,
      outputTokens: 1214,
      cacheTokens: 5301,
      cost: 0.03,
      time: 12,
      status: 'failed',
    },
    {
      id: 'sb-5',
      title: 'Story sorting incorrect with groups',
      url: 'https://github.com/example/storybook/issues/5',
      project: 'storybook',
      timestamp: '2025-10-05T11:20:00.000Z',
      inputTokens: 3522,
      outputTokens: 1463,
      cacheTokens: 7248,
      cost: 0.03,
      time: 11,
      status: 'succeeded',
    },
    {
      id: 'sb-6',
      title: 'Vite builder fails on TS path aliases',
      url: 'https://github.com/example/storybook/issues/6',
      project: 'storybook',
      timestamp: '2025-11-06T09:30:00.000Z',
      inputTokens: 4860,
      outputTokens: 1709,
      cacheTokens: 10028,
      cost: 0.04,
      time: 17,
      status: 'running',
    },
    {
      id: 'sb-7',
      title: 'A11y addon reports false positives',
      url: 'https://github.com/example/storybook/issues/7',
      project: 'storybook',
      timestamp: '2025-10-12T13:00:00.000Z',
      inputTokens: 2988,
      outputTokens: 1211,
      cacheTokens: 6140,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'sb-8',
      title: 'Controls addon not updating args',
      url: 'https://github.com/example/storybook/issues/8',
      project: 'storybook',
      timestamp: '2025-09-02T10:15:00.000Z',
      inputTokens: 3155,
      outputTokens: 1297,
      cacheTokens: 6502,
      cost: 0.02,
      time: 9,
      status: 'queued',
    },
    {
      id: 'sb-9',
      title: 'Types not emitted for story files',
      url: 'https://github.com/example/storybook/issues/9',
      project: 'storybook',
      timestamp: '2025-07-18T08:44:00.000Z',
      inputTokens: 3340,
      outputTokens: 1410,
      cacheTokens: 7015,
      cost: 0.03,
      time: 10,
      status: 'succeeded',
    },
    {
      id: 'sb-10',
      title: 'Storyshots migration plan',
      url: 'https://github.com/example/storybook/issues/10',
      project: 'storybook',
      timestamp: '2025-11-09T07:55:00.000Z',
      inputTokens: 5217,
      outputTokens: 1805,
      cacheTokens: 10866,
      cost: 0.05,
      time: 20,
      status: 'running',
    },
  ],
  'ci-pipeline': [
    {
      id: 'ci-1',
      title: 'Caching not used in Bun install',
      url: 'https://github.com/example/ci-pipeline/issues/1',
      project: 'ci-pipeline',
      timestamp: '2025-10-22T09:00:00.000Z',
      inputTokens: 4012,
      outputTokens: 1450,
      cacheTokens: 8129,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'ci-2',
      title: 'Flaky Playwright tests on macOS runners',
      url: 'https://github.com/example/ci-pipeline/issues/2',
      project: 'ci-pipeline',
      timestamp: '2025-11-04T10:10:00.000Z',
      inputTokens: 5321,
      outputTokens: 1840,
      cacheTokens: 10950,
      cost: 0.04,
      time: 16,
      status: 'running',
    },
    {
      id: 'ci-3',
      title: 'Docker layer caching not effective',
      url: 'https://github.com/example/ci-pipeline/issues/3',
      project: 'ci-pipeline',
      timestamp: '2025-09-14T12:30:00.000Z',
      inputTokens: 2877,
      outputTokens: 1355,
      cacheTokens: 5722,
      cost: 0.03,
      time: 11,
      status: 'succeeded',
    },
    {
      id: 'ci-4',
      title: 'Matrix builds exceed concurrency quota',
      url: 'https://github.com/example/ci-pipeline/issues/4',
      project: 'ci-pipeline',
      timestamp: '2025-08-20T08:00:00.000Z',
      inputTokens: 2699,
      outputTokens: 1222,
      cacheTokens: 5411,
      cost: 0.02,
      time: 9,
      status: 'queued',
    },
    {
      id: 'ci-5',
      title: 'Release job fails to upload assets',
      url: 'https://github.com/example/ci-pipeline/issues/5',
      project: 'ci-pipeline',
      timestamp: '2025-11-07T07:40:00.000Z',
      inputTokens: 4488,
      outputTokens: 1599,
      cacheTokens: 9002,
      cost: 0.05,
      time: 18,
      status: 'failed',
    },
    {
      id: 'ci-6',
      title: 'Cache restore too slow',
      url: 'https://github.com/example/ci-pipeline/issues/6',
      project: 'ci-pipeline',
      timestamp: '2025-10-03T10:00:00.000Z',
      inputTokens: 3122,
      outputTokens: 1409,
      cacheTokens: 6401,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'ci-7',
      title: 'PR labels automation',
      url: 'https://github.com/example/ci-pipeline/issues/7',
      project: 'ci-pipeline',
      timestamp: '2025-09-01T11:11:00.000Z',
      inputTokens: 2544,
      outputTokens: 1199,
      cacheTokens: 4988,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'ci-8',
      title: 'Secrets scanning in CI',
      url: 'https://github.com/example/ci-pipeline/issues/8',
      project: 'ci-pipeline',
      timestamp: '2025-07-12T14:20:00.000Z',
      inputTokens: 2333,
      outputTokens: 1155,
      cacheTokens: 4600,
      cost: 0.03,
      time: 10,
      status: 'queued',
    },
    {
      id: 'ci-9',
      title: 'Reusable workflows DRY-up',
      url: 'https://github.com/example/ci-pipeline/issues/9',
      project: 'ci-pipeline',
      timestamp: '2025-10-16T09:09:00.000Z',
      inputTokens: 3772,
      outputTokens: 1533,
      cacheTokens: 7620,
      cost: 0.03,
      time: 12,
      status: 'succeeded',
    },
    {
      id: 'ci-10',
      title: 'Self-hosted runners evaluation',
      url: 'https://github.com/example/ci-pipeline/issues/10',
      project: 'ci-pipeline',
      timestamp: '2025-11-10T10:10:00.000Z',
      inputTokens: 5901,
      outputTokens: 2050,
      cacheTokens: 11210,
      cost: 0.05,
      time: 20,
      status: 'running',
    },
  ],
  'icon-pack': [
    {
      id: 'ip-1',
      title: 'Missing 20px size for several icons',
      url: 'https://github.com/example/icon-pack/issues/1',
      project: 'icon-pack',
      timestamp: '2025-10-01T10:00:00.000Z',
      inputTokens: 2466,
      outputTokens: 1166,
      cacheTokens: 5011,
      cost: 0.02,
      time: 8,
      status: 'succeeded',
    },
    {
      id: 'ip-2',
      title: 'SVGs not optimized',
      url: 'https://github.com/example/icon-pack/issues/2',
      project: 'icon-pack',
      timestamp: '2025-11-03T09:30:00.000Z',
      inputTokens: 3177,
      outputTokens: 1299,
      cacheTokens: 6610,
      cost: 0.03,
      time: 10,
      status: 'running',
    },
    {
      id: 'ip-3',
      title: 'Icons not centered on baseline',
      url: 'https://github.com/example/icon-pack/issues/3',
      project: 'icon-pack',
      timestamp: '2025-09-18T12:45:00.000Z',
      inputTokens: 2840,
      outputTokens: 1205,
      cacheTokens: 5366,
      cost: 0.02,
      time: 9,
      status: 'succeeded',
    },
    {
      id: 'ip-4',
      title: 'Build script fails on Node 22',
      url: 'https://github.com/example/icon-pack/issues/4',
      project: 'icon-pack',
      timestamp: '2025-08-25T07:20:00.000Z',
      inputTokens: 3011,
      outputTokens: 1277,
      cacheTokens: 6205,
      cost: 0.03,
      time: 11,
      status: 'failed',
    },
    {
      id: 'ip-5',
      title: 'Add duotone variants',
      url: 'https://github.com/example/icon-pack/issues/5',
      project: 'icon-pack',
      timestamp: '2025-10-08T16:16:00.000Z',
      inputTokens: 3355,
      outputTokens: 1312,
      cacheTokens: 7021,
      cost: 0.04,
      time: 14,
      status: 'queued',
    },
    {
      id: 'ip-6',
      title: 'Tree-shaking not working in consumers',
      url: 'https://github.com/example/icon-pack/issues/6',
      project: 'icon-pack',
      timestamp: '2025-10-30T09:00:00.000Z',
      inputTokens: 3666,
      outputTokens: 1450,
      cacheTokens: 7411,
      cost: 0.04,
      time: 15,
      status: 'succeeded',
    },
    {
      id: 'ip-7',
      title: 'Stroke widths inconsistent',
      url: 'https://github.com/example/icon-pack/issues/7',
      project: 'icon-pack',
      timestamp: '2025-07-14T10:10:00.000Z',
      inputTokens: 2411,
      outputTokens: 1122,
      cacheTokens: 4899,
      cost: 0.02,
      time: 8,
      status: 'succeeded',
    },
    {
      id: 'ip-8',
      title: 'Missing RTL-mirrored icons',
      url: 'https://github.com/example/icon-pack/issues/8',
      project: 'icon-pack',
      timestamp: '2025-09-29T11:50:00.000Z',
      inputTokens: 2577,
      outputTokens: 1188,
      cacheTokens: 5200,
      cost: 0.03,
      time: 10,
      status: 'queued',
    },
    {
      id: 'ip-9',
      title: 'Add license headers',
      url: 'https://github.com/example/icon-pack/issues/9',
      project: 'icon-pack',
      timestamp: '2025-11-06T06:40:00.000Z',
      inputTokens: 3255,
      outputTokens: 1300,
      cacheTokens: 6622,
      cost: 0.03,
      time: 12,
      status: 'running',
    },
    {
      id: 'ip-10',
      title: 'Icon preview site',
      url: 'https://github.com/example/icon-pack/issues/10',
      project: 'icon-pack',
      timestamp: '2025-11-09T12:00:00.000Z',
      inputTokens: 4122,
      outputTokens: 1502,
      cacheTokens: 8120,
      cost: 0.05,
      time: 19,
      status: 'running',
    },
  ],
}

// Export sanitized fixtures without `description` (fixed literals only)
export const issuesByProject: Record<string, IssueDTO[]> = Object.fromEntries(
  Object.entries(issuesByProjectRaw).map(([project, issues]) => [
    project,
    issues,
  ])
)
