export const selectColumnId = 'select-column'
export const headerSelectCheckboxId = 'header-select-checkbox'
export const rowSelectCheckboxId = 'row-select-checkbox'

export const issueColumnId = 'issue-column'
export const descriptionColumnId = 'description-column'
export const timestampColumnId = 'timestamp-column'
export const inputTokensColumnId = 'input-tokens-column'
export const outputTokensColumnId = 'output-tokens-column'
export const cacheTokensColumnId = 'cache-tokens-column'
export const costColumnId = 'cost-column'
export const timeColumnId = 'time-column'
export const statusColumnId = 'status-column'

export const issueId = 'issue'
export const descriptionId = 'description'
export const timestampId = 'timestamp'
export const inputTokensId = 'input-tokens'
export const outputTokensId = 'output-tokens'
export const cacheTokensId = 'cache-tokens'
export const costId = 'cost'
export const timeId = 'time'
export const statusId = 'status'
export const issueRowId = 'issue-row'

export const totalsHeaderRowId = 'totals-header-row'
export const totalsFooterRowId = 'totals-footer-row'
// Standardised totals cell ids (used within the row via nested getByTestId)
export const totalsCellInputId = 'input'
export const totalsCellOutputId = 'output'
export const totalsCellCacheId = 'cache'
export const totalsCellCostId = 'cost'
export const totalsCellTimeId = 'time'

export const noDataMessageId = 'no-data-message'
export const loadingMessageId = 'loading-message'
export const errorMessageId = 'error-message'
