export const selectColumnId = 'select-column'
export const headerSelectCheckboxId = 'header-select-checkbox'
export const rowSelectCheckboxId = 'row-select-checkbox'

export const issueColumnId = 'issue-column'
export const descriptionColumnId = 'description-column'
export const timestampColumnId = 'timestamp-column'
export const inputTokensColumnId = 'input-tokens-column'
export const outputTokensColumnId = 'output-tokens-column'
export const cacheTokensColumnId = 'cache-tokens-column'
export const costColumnId = 'cost-column'
export const timeColumnId = 'time-column'
export const statusColumnId = 'status-column'

export const issueId = 'issue'
export const descriptionId = 'description'
export const timestampId = 'timestamp'
export const inputTokensId = 'input-tokens'
export const outputTokensId = 'output-tokens'
export const cacheTokensId = 'cache-tokens'
export const costId = 'cost'
export const timeId = 'time'
export const statusId = 'status'
export const issueRowId = 'issue-row'

export const totalsHeaderRowId = 'totals-header-row'
export const totalsFooterRowId = 'totals-footer-row'
export const totalsHeaderInputId = 'totals-header-input'
export const totalsHeaderOutputId = 'totals-header-output'
export const totalsHeaderCacheId = 'totals-header-cache'
export const totalsHeaderCostId = 'totals-header-cost'
export const totalsHeaderTimeId = 'totals-header-time'
export const totalsFooterInputId = 'totals-footer-input'
export const totalsFooterOutputId = 'totals-footer-output'
export const totalsFooterCacheId = 'totals-footer-cache'
export const totalsFooterCostId = 'totals-footer-cost'
export const totalsFooterTimeId = 'totals-footer-time'

export const noDataMessageId = 'no-data-message'
export const loadingMessageId = 'loading-message'
export const errorMessageId = 'error-message'
